### ISSUE TITLE
Demo gets stuck cycling through routes

### ISSUE THREAD

**Issue by ghost** [ebidel/polymer-change#2]
If you repeatedly click on the 'page' very quickly the app gets stuck in a continuous loop. Tested on Chrome 37 on Mavericks. Not sure whats going on but looks like a mini one to fix before we can use polymer to create larger SPA's.

**Comment by ebidel** [comment]
Hmm, not seeing this on 38 beta. If you can reliable repo on 38 beta, let me know. 

The "click to change page" feature is only a convenience in the demo. I'm also not sure users will click pages as fast as they can in a real-world app :)
